Projetos padronizados e checados
EduardoLR10/UNIX-SYS-libs-tests pull request #5
Opened 2020-11-02 21:17 UTC by EduardoLR10

Eu li o trabalho do Pedro e mesmo tendo dificuldade de identificar se havia algum problema com a implementação dele, eu decidi refazer usando a sugestão da professora em sala para garantir que vai dar bom. Padronizei cabeçalhos em todos.

2020-11-03 13:52 UTC, pelu97 approved these changes

2020-11-05 01:42 UTC, GiordanoSM submitted a review, later dismissed
Tá faltando o nome e matrícula do Pedro no cabeçalho do trabalho 1, e segunda versão do gcc ta diferente dos outros. bytes_read não utilizado na linha 68.

2020-11-05 02:04 UTC, EduardoLR10 commented
Adicionei a matrícula do Pedro no trabalho 1 e removi a variável desnecessária do trabalho 3. Não me responsabilizo pela padronização das versões do gcc (validei apenas o uso da versão 5.4.0 que foi a que usei).

2020-11-05 02:17 UTC, GiordanoSM requested changes
Comparação errada na verificação de criação dos semáforos no trabalho2.c . Deve ser semget() < 0 e não < -1.

2020-11-05 02:23 UTC, EduardoLR10 commented
Padronizei todas as checagem de erro para == -1.

2020-11-05 02:25 UTC, GiordanoSM approved these changes

2020-11-09 13:09 UTC, Shothogun commented on trabalho3.c
> +        pausa = rand() % 4;
Se é de um a 4 segundos, não deveria ser % 5?

2020-11-09 13:15 UTC, GiordanoSM commented on trabalho3.c
> +        pausa = rand() % 4;
Pelo que entendi os resultados de  %4 vao ser 0, 1, 2 ou 3 né. Ai pra ficar de 1 a 4 sec ele tá somando 1 à pausa logo na linha debaixo.

2020-11-09 13:21 UTC, pelu97 commented on trabalho3.c
> +        pausa = rand() % 4;
Exatamente isso, porque %5 daria de 0 a 4, mas a especificação pede de 1 a 4, então faço de 0 a 3 (%4) e somo 1

2020-11-09 13:23 UTC, pelu97 approved these changes

2020-11-09 16:05 UTC, Shothogun approved these changes

2020-11-09 16:05 UTC, merged

2020-11-09 17:04 UTC, EduardoLR10 commented on trabalho3.c
> +        pausa++;
A operação de resto da linha 41 vai devolver um número de 0 a 3. A linha 43 é oq nos coloca entre 1 e 4.